### ISSUE TITLE
Cannot find module 'async'

### ISSUE THREAD

**Issue by yvanavermaet** [jonschlinkert/templates#13]
Hi

We're using a module named "assemble" and this module uses this one. The modules are installed with a "--production" flag. When using the assemble module, the following error occurs:

> Error: Cannot find module 'async'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:286:25)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (/var/app/buildslave/jenkins/workspace/Team Awesom-O/APM/APM Frontend/APM Frontend - deploy DEV/node_modules/assemble/node_modules/assemble-core/node_modules/templates/lib/plugins/context.js:3:13)

It seems the context.js file uses the async-module, but according to the package.json, this should just be a devDependency. I believe that's where the problem is located.

If you need any more information, let me know.

Kind regards,
Yannick

**Comment by doowb** [comment]
Thanks for pointing this out. We'll get it fixed.

**Comment by doowb** [comment]
Fixed in `0.13.4`. You should be able to reinstall `assemble` to get the latest.

**Comment by yvanavermaet** [comment]
@doowb Works like a charm, thx for the fast fix!
