### ISSUE TITLE
Layouts not working as expected

### ISSUE THREAD

**Issue by tjbenton** [jonschlinkert/templates#25]
After setting everything up setting the `layout` on the `index.pug` file to be `_layout` and rendering it. This is what the output is.

**Note:** Below are the files that I used.

**Actual:**

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
  </body>
</html>
<ul>
  <li>item</li>
  <li>item</li>
  <li>item</li>
  <li>item</li>
</ul>
<h1>Partial</h1>
```
##### Expected

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
    <ul>
      <li>item</li>
      <li>item</li>
      <li>item</li>
      <li>item</li>
    </ul>
    <h1>Partial</h1>
  </body>
</html>
```

`_layout.pug`

``` pug
doctype html
html
  head
    meta(charset="utf-8")
  body
    {% body %}
```

`index.pug`

``` pug
p Lorem ipsum dolor sit amet, consectetur adipisicing elit.

ul
  li item
  li item
  li item
  li item

!= helpers.partial('_partial')
```

`_partial.pug`

``` pug
h1 Partial
```

**Comment by jonschlinkert** [comment]
> After setting everything up setting the layout on the index.pug

what's `.pug`? Are you using a custom engine?

**Comment by tjbenton** [comment]
It's an engine supported by `consolidate` it was formally jade 

https://pugjs.org

**Comment by tjbenton** [comment]
I think that the reason why it's not working is because `jade`/`pug` is an indention based language and when the files are rendered they aren't being indented to the point that the `{% body %}` tag is being indented. Only the first line that was rendered was in the correct spot but after the first `\n` that's when the content get's placed in the wrong position.

**Comment by jonschlinkert** [comment]
Can you paste your entire configuration here please.

**Comment by tjbenton** [comment]
This isn't my exact config but it gives you the same result that I mentioned above. 

``` js
import templates from 'templates'
import consolidate from 'consolidate'

const app = templates()

app.create('pages')
app.create('layouts', { viewType: 'layout' })
app.create('partials', { viewType: 'partial' })

// pretty is just to format the html instead of it being minified
app.engine('pug', consolidate.pug, { pretty: true })

app.layout('_layout.pug', {
  content: [
    'doctype html',
    'html',
    '  head',
    '    meta(charset="utf-8")',
    '    title test',
    '  body',
    '    {% body %}',
  ].join('\n')
})

app.partial('_partial.pug', { content: 'h1 Partial\n' })

app.page('index.pug', {
  content: [
    'p Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    '',
    'ul',
    '  li item',
    '  li item',
    '  li item',
    '  li item',
    '',
    '!= helpers.partial(\'_partial\')',
  ].join('\n'),
  layout: '_layout'
})


app.render('index', (err, { content }) => {
  if (err) {
    console.log(err)
    return
  }

  console.log(content);
})
```

**Comment by jonschlinkert** [comment]
your whitespace is wrong, causing pug to generate the wrong HTML. Try this:

``` js
var templates = require('templates');
var consolidate = require('consolidate');
var app = templates();

app.create('pages');
app.create('layouts', { viewType: 'layout' });
app.create('partials', { viewType: 'partial' });

// pretty is just to format the html instead of it being minified
app.engine('pug', consolidate.pug, { pretty: true });

app.layout('_layout.pug', {
  content: [
    'doctype html',
    'html',
    '  head',
    '    meta(charset="utf-8")',
    '    title test',
    '  body',
    '{% body %}',
  ].join('\n')
});

app.partial('_partial.pug', { content: 'h1 Partial\n' });

app.page('index.pug', {
  content: [
    '    p Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    '    ',
    '    ul',
    '      li item',
    '      li item',
    '      li item',
    '      li item',
    '    ',
    '    != helpers.partial(\'_partial\')',
  ].join('\n'),
  layout: '_layout'
});

app.render('index.pug', function(err, res) {
  if (err) {
    console.log(err);
    return;
  }
  console.log(res.contents.toString());
});
```

**Comment by jonschlinkert** [comment]
keep in mind that whitespacing is preserved exactly as-is, no "corrections" are made

edit: also as a rule of thumb, don't use code that needs to be transpiled in examples. It makes it harder to debug

**Comment by tjbenton** [comment]
That seems a little odd to me. If I create a file like `index.pug` I wouldn't expect to have to put 4 spaces in front of the first `p` tag. I would just start my file with my `p` tag like I normally do for most templating languages. This would require me to know exactly how far I need to indent on every layout I add.

I'm trying to create an app for my design team that allows them to write just the body of emails and they would have to put 50 plus spaces in front of each line in order to use the layout feature.

Would there be a way to add in corrections in there as an option? Like being able to specify the indent for the template that was added?

**Comment by jonschlinkert** [comment]
> This would require me to know exactly how far I need to indent on every layout I add.

This is a good point. Let me think about how we can work around this. I have some ideas, I don't think it will be too terribly difficult. We just need to calculate leading whitespace for the `{% body %}` tag, then prefix each line in the injected string with the same amount of whitespace.

> Would there be a way to add in corrections in there as an option? Like being able to specify the indent for the template that was added?

Until we implement a solution for this, you might be able to create a helper or something that preserves whitespace for you.

**Comment by jonschlinkert** [comment]
I'm going to close this and open a new issue related to whitespace, since (technically) this issue is resolved.
